# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - momowebapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0e03c0b895104ed2af5276d6b30ba836 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61220baefe424112adbcd4e650c41e5e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0e03c0b895104ed2af5276d6b30ba836 }}/momo90/helloworldservice:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'momowebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2b1848251b4d4ddf9ceb07ed2fa51086 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0e03c0b895104ed2af5276d6b30ba836 }}/momo90/helloworldservice:${{ github.sha }}'